// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuNmtXOnPDgb3iCNo7Pl-modLvjFYfI0s',
    appId: '1:70496179969:web:321b4bba9e4772428c2d00',
    messagingSenderId: '70496179969',
    projectId: 'brewlog-60271',
    authDomain: 'brewlog-60271.firebaseapp.com',
    storageBucket: 'brewlog-60271.firebasestorage.app',
    measurementId: 'G-EVEV42S2J3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAv5-KWkzBGXQ9IbtbwUWNjV537qrTgNgs',
    appId: '1:70496179969:android:5e74bfabe116d7438c2d00',
    messagingSenderId: '70496179969',
    projectId: 'brewlog-60271',
    storageBucket: 'brewlog-60271.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCicvbJKMQIKdBv9kyh7NjvHo_eVzDZ_hM',
    appId: '1:70496179969:ios:3e5c0f1b774baa398c2d00',
    messagingSenderId: '70496179969',
    projectId: 'brewlog-60271',
    storageBucket: 'brewlog-60271.firebasestorage.app',
    iosBundleId: 'com.Kohnqueror.BrewLog',
  );
}
