import 'dart:async'; // Import for StreamSubscription
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart'; // Import for RemoteMessage
import 'screens/login_screen.dart';
import 'screens/home_screen.dart';
import 'providers/auth_provider.dart';
import 'providers/theme_provider.dart';
import 'firebase_options.dart'; // This file is generated by FlutterFire

Future<void> main() async { // Make main async
  // --- NEW: Initialize Firebase ---
  WidgetsFlutterBinding.ensureInitialized(); // Required before Firebase init
  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform, // Use generated options
    );
    print("Firebase initialized successfully");
  } catch (e) {
    print("Failed to initialize Firebase: $e");
    // Handle initialization error if necessary
  }
  // --- END NEW ---

  runApp(
    MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => AuthProvider()),
        ChangeNotifierProvider(create: (_) => ThemeProvider()),
      ],
      child: const DrinkTrackerApp(),
    ),
  );
}

class DrinkTrackerApp extends StatelessWidget {
  const DrinkTrackerApp({super.key});

  @override
  Widget build(BuildContext context) {
    return Consumer<ThemeProvider>(
      builder: (context, themeProvider, child) {
        return MaterialApp(
          title: 'BrewLog', // Updated App Title
          theme: themeProvider.lightTheme,
          darkTheme: themeProvider.darkTheme,
          themeMode: themeProvider.themeMode,
          home: const AuthCheck(),
          debugShowCheckedModeBanner: false, // Optional: Hide debug banner
        );
      },
    );
  }
}

class AuthCheck extends StatefulWidget {
  const AuthCheck({super.key});

  @override
  State<AuthCheck> createState() => _AuthCheckState();
}

class _AuthCheckState extends State<AuthCheck> {
  // --- NEW: Stream Subscription ---
  StreamSubscription<RemoteMessage>? _notificationSubscription;
  // --- END NEW ---

  @override
  void initState() {
    super.initState();
    // --- MODIFIED: Use addPostFrameCallback ---
    WidgetsBinding.instance.addPostFrameCallback((_) {
      // Check if mounted before accessing context
      if (!mounted) return;

      final authProvider = Provider.of<AuthProvider>(context, listen: false);
      authProvider.checkAuth();

      // --- NEW: Listen to the notification stream ---
      _notificationSubscription = authProvider.notificationStream.listen(_showNotificationBanner);
      // --- END NEW ---
    });
  }

  // --- NEW: Show SnackBar Banner ---
  void _showNotificationBanner(RemoteMessage message) {
    // Ensure context is still mounted
    if (!mounted) return;

    final notification = message.notification;
    if (notification == null) return;

    // Use the ScaffoldMessenger from the root
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        content: Column(
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(notification.title ?? 'New Notification', style: const TextStyle(fontWeight: FontWeight.bold)),
            if (notification.body != null)
              Text(notification.body!),
          ],
        ),
        behavior: SnackBarBehavior.floating, // Makes it a banner
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
        margin: const EdgeInsets.all(10),
        duration: const Duration(seconds: 4),
      ),
    );
  }
  // --- END NEW ---

  // --- NEW: Dispose Subscription ---
  @override
  void dispose() {
    _notificationSubscription?.cancel();
    super.dispose();
  }
  // --- END NEW ---

  @override
  Widget build(BuildContext context) {
    return Consumer<AuthProvider>(
      builder: (context, auth, child) {
        if (auth.isAuthenticated) {
          return const HomeScreen();
        } else {
          return const LoginScreen();
        }
      },
    );
  }
}